### ISSUE TITLE
Osmosis and Terra research

### ISSUE THREAD

**Issue by mastercyb** [cybercongress/cw-cybergift#7]

**Comment by mastercyb** [comment]
@serejandmyself Как ты думаешь - можешь вообще обрежем адреса в аномалии у Терры?

**Comment by mastercyb** [comment]
Added to drop

**Comment by Snedashkovsky** [comment]
https://github.com/Snedashkovsky/cybergift/pull/48

**Comment by Snedashkovsky** [comment]
https://github.com/Snedashkovsky/cybergift/pull/47
